"""
RAILBLOCK AI — SQLAlchemy Declarative Base

All ORM models must inherit from RailBlockBase.
Provides common columns (id, created_at, updated_at) for every table.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def utcnow() -> datetime:
    """Return current UTC datetime (timezone-aware)."""
    return datetime.now(timezone.utc)


class RailBlockBase(DeclarativeBase):
    """
    Abstract base class for all RAILBLOCK AI database models.

    Every table gets:
    - id          UUID primary key (generated by the DB)
    - created_at  Timestamp of record creation
    - updated_at  Timestamp of last update (auto-maintained)
    """

    # Instruct SQLAlchemy to NOT create a table for this base class itself
    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
        comment="Universally unique identifier for this record",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        nullable=False,
        comment="UTC timestamp when the record was created",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
        nullable=False,
        comment="UTC timestamp when the record was last updated",
    )

    def to_dict(self) -> dict:
        """Serialize model to a plain dict (for debugging / logging)."""
        return {
            col.name: getattr(self, col.name)
            for col in self.__table__.columns
        }


# ---------------------------------------------------------------------------
# Re-export for convenience: all models import Base from here
# ---------------------------------------------------------------------------

Base = RailBlockBase
