"""
RAILBLOCK AI — TMS Adapter (SIMULATED)

[SIMULATION] This adapter generates synthetic Train Management System data.
It does NOT connect to any real TMS.
All data produced is labeled SIMULATED_TMS.

When authorized TMS API access is available, this class can be replaced
with a real implementation that conforms to the DataSourceAdapter protocol.
"""
from __future__ import annotations
import random
from datetime import datetime, timedelta, timezone
from typing import Any
from app.adapters.base_adapter import AdapterResult, AdapterRecord

_TASK_CATEGORIES = ["TRACK", "SIGNAL", "CIVIL", "ELECTRICAL", "MECHANICAL"]
_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
_TMS_TASKS = [
    ("Track geometry correction at km 23.5", "TRACK"),
    ("Rail joint welding", "TRACK"),
    ("Level crossing gate maintenance", "CIVIL"),
    ("Overhead catenary inspection", "ELECTRICAL"),
    ("Signal head replacement", "SIGNAL"),
    ("Point and crossing lubrication", "MECHANICAL"),
    ("Ballast compaction at km 45", "TRACK"),
    ("Drainage clearing after monsoon", "CIVIL"),
]

class SimulatedTMSAdapter:
    """
    [SIMULATED_TMS] Synthetic Train Management System Adapter.
    
    Generates realistic-looking maintenance tasks for demonstration.
    NOT connected to Indian Railways TMS.
    """

    source_system_name = "SIMULATED_TMS"
    is_simulated = True

    async def fetch_maintenance_requests(self, limit: int = 50) -> AdapterResult:
        now = datetime.now(timezone.utc)
        records = []
        for i in range(min(limit, 10)):
            title, category = random.choice(_TMS_TASKS)
            rec_id = f"TMS-{random.randint(10000, 99999)}"
            records.append(AdapterRecord(
                source_system="SIMULATED_TMS",
                source_record_id=rec_id,
                source_timestamp=now - timedelta(hours=random.randint(1, 72)),
                record_type="MaintenanceRequest",
                payload={
                    "title": f"[SIMULATED_TMS] {title}",
                    "category": category,
                    "priority": random.choice(_PRIORITIES),
                    "estimated_duration_hours": round(random.uniform(2, 12), 1),
                    "requires_block": True,
                    "source_system": "SIMULATED_TMS",
                    "source_record_id": rec_id,
                    "source_timestamp": (now - timedelta(hours=random.randint(1, 72))).isoformat(),
                    "import_timestamp": now.isoformat(),
                    "description": f"Synthetic task generated by SIMULATED_TMS adapter (not real IR data)",
                },
                is_simulated=True,
            ))
        return AdapterResult(
            source_system="SIMULATED_TMS",
            records=records,
            is_simulated=True,
            fetched_at=now,
        )

    async def fetch_defects(self, limit: int = 50) -> AdapterResult:
        now = datetime.now(timezone.utc)
        defect_types = ["Rail fracture reported", "Gauge deviation at crossing", "Loose fishbolts"]
        records = []
        for i in range(min(limit, 5)):
            rec_id = f"TMS-DEF-{random.randint(1000, 9999)}"
            records.append(AdapterRecord(
                source_system="SIMULATED_TMS",
                source_record_id=rec_id,
                source_timestamp=now - timedelta(hours=random.randint(1, 48)),
                record_type="Defect",
                payload={
                    "description": f"[SIMULATED_TMS] {random.choice(defect_types)}",
                    "severity": random.choice(["MINOR", "MODERATE", "MAJOR"]),
                    "source_system": "SIMULATED_TMS",
                    "source_record_id": rec_id,
                },
                is_simulated=True,
            ))
        return AdapterResult(
            source_system="SIMULATED_TMS",
            records=records,
            is_simulated=True,
            fetched_at=now,
        )

    async def health_check(self) -> dict[str, Any]:
        return {
            "adapter": "SimulatedTMSAdapter",
            "source_system": "SIMULATED_TMS",
            "status": "ok",
            "is_simulated": True,
            "note": "This adapter generates synthetic data. Not connected to real TMS.",
        }
